# ----------------------- #
#      Main Configs       #
# ----------------------- #
title:            落园
description:      "专注经济视角下的互联网"
paginate:         8
permalink: /blog/:year/:month/:day/:title

#baseurl: /loyhome

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

markdown: maruku

# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

#douban
douban_user:

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

#weibo
weibo_user:

# Twitter
twitter_user:
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false

# ----------------------- #
#   blogroll links        #
# ----------------------- #

links: 
    - name: 雁起平沙
      url: http://yanping.me
      disc: 

    - name: "Blogkid&#039;s 做最好的自己"
      url: http://www.blogkid.net/
      disc: 认识很久的磊哥哥